/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;
import clases.conectar;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.JOptionPane;


public class formulario extends javax.swing.JFrame {
    conectar conecto;
    
    PreparedStatement ps;
    ResultSet rs;
    
    private static Connection conn;
    private static final String driver = "com.mysql.jdbc.Driver";
    private static final String user = "root";
    private static final String pass = "";
    private static final String url = "jdbc:mysql://localhost:3306/pañalera";
    
    public formulario(){
        initComponents();
    }
    
    public Connection getConnection(){
        Connection conn=null;
        try {
            Class.forName(driver);
            conn = DriverManager.getConnection(url, user, pass);
            if(conn !=null) {
                System.out.println("La conexion se establecio bien con la DB");
            }
            
        } catch (ClassNotFoundException | SQLException e ) {
            System.out.println("Error al conectar con la DB" + e);
        }
        return conn;
    }
    
    public void Desconectar (){
        conn=null;
        if (conn == null) {
            System.out.println("Se desconecto la Db");
           
        }
    }    
    
    public void borrarCajas (){
        cajanombre.setText(null);
        cajaproducto.setText(null);
        cajacantidad.setText(null);
        
        
    }

    /**
     * Creates new form formulario
     */
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cajanombre = new javax.swing.JTextField();
        cajaproducto = new javax.swing.JTextField();
        cajacantidad = new javax.swing.JTextField();
        bconectar = new javax.swing.JButton();
        bdesconectar = new javax.swing.JButton();
        benviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 80, 20));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Producto:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 90, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Cantidad:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 80, 30));

        cajanombre.setBackground(new java.awt.Color(51, 204, 255));
        getContentPane().add(cajanombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 170, -1));

        cajaproducto.setBackground(new java.awt.Color(51, 204, 255));
        getContentPane().add(cajaproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 160, -1));

        cajacantidad.setBackground(new java.awt.Color(51, 204, 255));
        getContentPane().add(cajacantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 160, -1));

        bconectar.setText("conectar");
        bconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bconectarActionPerformed(evt);
            }
        });
        getContentPane().add(bconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        bdesconectar.setText("Desconectar");
        bdesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdesconectarActionPerformed(evt);
            }
        });
        getContentPane().add(bdesconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, -1, -1));

        benviar.setText("Enviar");
        benviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                benviarActionPerformed(evt);
            }
        });
        getContentPane().add(benviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pañaker_preview_rev_1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 200, 200));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel5.setText("PAÑALERA MI COLITA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 380, 50));

        jfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/27335690-vector-bebé-muchachos-del-fondo-del-modelo-horizontal-sin-fisuras-con-elementos-dibujados-a-mano-.jpg"))); // NOI18N
        getContentPane().add(jfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bconectarActionPerformed
         conecto = new conectar();
        Connection reg = conecto.getConnection();
    }//GEN-LAST:event_bconectarActionPerformed

    private void bdesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdesconectarActionPerformed
         conecto.Desconectar();
    }//GEN-LAST:event_bdesconectarActionPerformed

    private void benviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_benviarActionPerformed
        Connection conn = null;
        
        try {
            conn = getConnection();
            ps = conn.prepareStatement("INSERT INTO datos (nombrecliente, producto, cantidad, fechareg) VALUES(?,?,?,?)");
            ps.setString(1, cajanombre.getText());
            ps.setString(2, cajaproducto.getText());
            ps.setString(3, cajacantidad.getText());
            ps.setDate(4, Date.valueOf(LocalDate.now()));
            
            int result = ps.executeUpdate();
            if (result > 0) {
                JOptionPane.showMessageDialog(null, "Los datos fueron enviados correctamente");
                borrarCajas();
            }else{
                JOptionPane.showMessageDialog(null, "Los datos no fueron enviados");
            }
            conn.close();
            
            
        } catch (Exception e){
            System.out.println(e);
            
        }
    }//GEN-LAST:event_benviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
     public void run() {
                new formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bconectar;
    private javax.swing.JButton bdesconectar;
    private javax.swing.JButton benviar;
    private javax.swing.JTextField cajacantidad;
    private javax.swing.JTextField cajanombre;
    private javax.swing.JTextField cajaproducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jfondo;
    // End of variables declaration//GEN-END:variables
}
